#!/usr/bin/env bash

#rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
rm ~/.config/nvim
ln -s $(pwd) ~/.config/nvim
git clone --depth 1 https://github.com/wbthomason/packer.nvim  ~/.local/share/nvim/site/pack/packer/start/packer.nvim
