-- local neodev = require('lazydev')
-- neodev.setup({
--     ft = "lua",
--     library = {
--         plugins = { "nvim-dap-ui", "nvim-treesitter", "plenary.nvim", "telescope.nvim" },
--         types = true
--     },
-- })
